name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:    
    - uses: actions/checkout@v1
    - name: Login DockerHub
      uses: actions/docker/login@master
      env: 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build the Docker image
      uses: actions/docker/cli@master
      with:
        args: build . --file Dockerfile --tag kubemates/go-inception:latest
    - name: Push the Docker image step1
      uses: actions/docker/cli@master
      with:
        args: push kubemates/go-inception:latest
